name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Use the latest stable version

      - run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Make distributable
        run: npx electron-builder --${{ matrix.os }}
